app/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app, abort, send_file
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt, scheduler
from app.forms import RegistrationForm, LoginForm, AddPetForm, PetHistoryForm, VetAppointmentForm, VaccineTrackingForm, EditVaccineForm, FeedingScheduleForm, ExpenseForm
from app.models import User, Pet, PetHistory, VetAppointment, VaccineRecord, FeedingSchedule, Expense
from app.utils import send_verification_email, confirm_verification_token, send_appointment_email, send_reminder_email
from werkzeug.utils import secure_filename
import os
from datetime import datetime, timedelta, date
from weasyprint import HTML
import io

bp = Blueprint('main', __name__)

# Home route, displays the home page
@bp.route("/")
@bp.route("/home")
def home():
    return render_template('index.html')

# Registration route, handles user registration
@bp.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        send_verification_email(user)
        flash('An email has been sent to verify your account.', 'info')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)

# Login route, handles user login
@bp.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            if user.is_verified:
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.dashboard'))
            else:
                flash('Your account is not verified. Please check your email.', 'warning')
                return redirect(url_for('main.login'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

# Logout route, logs out the current user
@bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

# Dashboard route, displays the user dashboard with pets, appointments, and expenses
@bp.route("/dashboard")
@login_required
def dashboard():
    now = datetime.now()
    due_appointments = VetAppointment.query.filter(
        (VetAppointment.date < now.date()) | 
        ((VetAppointment.date == now.date()) & (VetAppointment.time <= now.time()))
    ).all()
    for appointment in due_appointments:
        history_event = PetHistory(
            event_type='Vet Appointment',
            event_date=appointment.date,
            event_time=appointment.time,
            description=appointment.description,
            pet_id=appointment.pet_id
        )
        db.session.add(history_event)
        db.session.delete(appointment)
    db.session.commit()

    pets = Pet.query.filter_by(user_id=current_user.id).all()
    appointments = VetAppointment.query.join(Pet).filter(Pet.user_id == current_user.id).all()
    closest_vaccine_record = VaccineRecord.query.join(Pet).filter(
        Pet.user_id == current_user.id,
        VaccineRecord.next_due_date >= date.today()
    ).order_by(VaccineRecord.next_due_date).first()
    total_expenses = db.session.query(db.func.sum(Expense.amount)).join(Pet).filter(Pet.user_id == current_user.id).scalar() or 0.0

    return render_template(
        'dashboard.html', 
        title='Dashboard', 
        pets=pets, 
        appointments=appointments,
        closest_vaccine_record=closest_vaccine_record,
        total_expenses=total_expenses
    )

# Email confirmation route, confirms user email address
@bp.route("/confirm_email/<token>")
def confirm_email(token):
    email = confirm_verification_token(token)
    if email:
        user = User.query.filter_by(email=email).first_or_404()
        if user.is_verified:
            flash('Account already verified. Please log in.', 'success')
        else:
            user.is_verified = True
            db.session.commit()
            flash('Your account has been verified!', 'success')
    else:
        flash('The confirmation link is invalid or has expired.', 'danger')
    return redirect(url_for('main.login'))

# Route to delete all users, for testing or administrative purposes
@bp.route("/delete_all_users")
def delete_all_users():
    users = User.query.all()
    for user in users:
        pets = Pet.query.filter_by(user_id=user.id).all()
        for pet in pets:
            FeedingSchedule.query.filter_by(pet_id=pet.id).delete(synchronize_session=False)
            Expense.query.filter_by(pet_id=pet.id).delete(synchronize_session=False)
            VaccineRecord.query.filter_by(pet_id=pet.id).delete(synchronize_session=False)
            PetHistory.query.filter_by(pet_id=pet.id).delete(synchronize_session=False)
            VetAppointment.query.filter_by(pet_id=pet.id).delete(synchronize_session=False)
            db.session.delete(pet)
        db.session.delete(user)
    db.session.commit()
    return "All users, their pets, and their histories have been deleted.", 200

# Route for managing pets, displays the pet management page
@bp.route("/manage_pets")
@login_required
def manage_pets():
    pets = Pet.query.filter_by(user_id=current_user.id).all()
    return render_template('manage_pets.html', title='Pet Management', pets=pets)

# Route for adding a pet, handles the addition of a new pet
@bp.route("/add_pet", methods=['GET', 'POST'])
@login_required
def add_pet():
    form = AddPetForm()
    if form.validate_on_submit():
        picture_file = secure_filename(form.picture.data.filename)
        picture_path = os.path.join(current_app.root_path, 'static/pet_pics', picture_file)
        form.picture.data.save(picture_path)
        pet = Pet(
            name=form.name.data, 
            age=form.age.data, 
            breed=form.breed.data, 
            gender=form.gender.data,
            picture=picture_file, 
            user_id=current_user.id
        )
        db.session.add(pet)
        db.session.commit()
        flash('Your pet has been added!', 'success')
        return redirect(url_for('main.dashboard'))
    return render_template('add_pet.html', title='Add Pet', form=form)

# Route for editing a pet, handles the editing of pet details
@bp.route("/edit_pet/<int:pet_id>", methods=['GET', 'POST'])
@login_required
def edit_pet(pet_id):
    pet = Pet.query.get_or_404(pet_id)
    if pet.owner != current_user:
        flash('You do not have permission to edit this pet.', 'danger')
        return redirect(url_for('main.manage_pets'))
    
    form = AddPetForm(obj=pet)
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = secure_filename(form.picture.data.filename)
            picture_path = os.path.join(current_app.root_path, 'static/pet_pics', picture_file)
            form.picture.data.save(picture_path)
            pet.picture = picture_file

        pet.name = form.name.data
        pet.age = form.age.data
        pet.breed = form.breed.data
        pet.gender = form.gender.data

        db.session.commit()
        flash('Your pet has been updated!', 'success')
        return redirect(url_for('main.dashboard'))

    return render_template('edit_pet.html', title='Edit Pet', form=form)

# Route to delete a pet, handles the deletion of a pet and its associated data
@bp.route("/delete_pet/<int:pet_id>", methods=['POST'])
@login_required
def delete_pet(pet_id):
    pet = Pet.query.get_or_404(pet_id)
    if pet.owner != current_user:
        flash('You do not have permission to delete this pet.', 'danger')
        return redirect(url_for('main.manage_pets'))

    PetHistory.query.filter_by(pet_id=pet.id).delete(synchronize_session=False)
    VetAppointment.query.filter_by(pet_id=pet.id).delete(synchronize_session=False)
    VaccineRecord.query.filter_by(pet_id=pet.id).delete(synchronize_session=False)
    FeedingSchedule.query.filter_by(pet_id=pet.id).delete(synchronize_session=False)
    Expense.query.filter_by(pet_id=pet.id).delete(synchronize_session=False)

    db.session.delete(pet)
    db.session.commit()
    flash('The pet and its history have been deleted!', 'success')
    return redirect(url_for('main.manage_pets'))

# Route for viewing and adding pet history, handles displaying and adding history events
@bp.route("/pet/<int:pet_id>/history", methods=['GET', 'POST'])
@login_required
def pet_history(pet_id):
    pet = Pet.query.get_or_404(pet_id)
    if pet.owner != current_user:
        abort(403)

    form = PetHistoryForm()
    if form.validate_on_submit():
        history_event = PetHistory(
            event_type=form.event_type.data,
            event_date=form.event_date.data,
            event_time=form.event_time.data,
            description=form.description.data,
            pet_id=pet.id
        )
        db.session.add(history_event)
        db.session.commit()
        flash('History event added!', 'success')
        return redirect(url_for('main.pet_history', pet_id=pet.id))
    
    history_events = PetHistory.query.filter_by(pet_id=pet.id).all()
    for event in history_events:
        event.formatted_date = event.event_date.strftime('%A, %B %d, %Y')
        event.formatted_time = event.event_time.strftime('%I:%M %p')
    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <style>
        .navbar-custom {
            background-color: #e6e6e6; /* Light grey color */
            height: 75px; /* Shorter height */
        }
        .navbar-custom .nav-link {
            color: black; /* Black button color */
            font-weight: 700; /* Make the text bold */
            font-size: 16px; /* Increase font size */
            padding: 15px 10px; /* Adjust padding for closer spacing */
            border-radius: 10px; /* Rounded corners for the box */
            transition: background-color 0.3s; /* Smooth transition */
        }
        .navbar-custom .nav-link:hover {
            background-color: rgba(0, 0, 0, 0.1); /* Highlight on hover */
        }
        .navbar-brand {
            color: black; /* Change text color to black */
            font-size: 24px; /* Adjust font size */
            font-weight: bold; /* Make the text bold */
            text-decoration: none; /* Remove underline */
        }
        .navbar-brand .paw-icon {
            margin-right: 10px;
            color: black; /* Black paw icon color */
        }
        .navbar-custom .navbar-toggler-icon {
            background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba%280, 0, 0, 0.5%29' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
        }
        .navbar-secondary {
            background-color: #1b1b1b; /* Dark grey color */
            height: 40px; /* Shorter height */
            display: flex;
            align-items: center;
            justify-content: center; /* Center the content */
            color: white; /* White text color */
            position: relative;
        }
        .navbar-secondary .contact-text {
            position: absolute;
            left: 50%;
            transform: translateX(-50%);
            text-align: center; /* Center the contact text */
        }
        .navbar-secondary .user-email {
            color: white; /* Change user email color to white */
            margin-left: auto; /* Push user email to the right */
        }
        .navbar-secondary .auth-buttons {
            margin-left: auto; /* Push auth buttons to the right */
            display: flex;
            gap: 10px;
        }
        .navbar-secondary .auth-buttons .nav-link {
            color: white; /* White text color for auth buttons */
        }
        .navbar-tertiary {
            background-color: #71a2cf; /* Blue color */
            display: flex;
            align-items: center; /* Center horizontally */
            justify-content: center; /* Center vertically */
            color: rgb(255, 255, 255); /* White text color */
            border-bottom-left-radius: 15%; /* Add curved border to bottom left corner */
            border-bottom-right-radius: 15%; /* Add curved border to bottom right corner */
            box-shadow: 0px -5px 5px rgba(0, 0, 0, 0); /* Add shadow to create depth */
            transform: translateY(1px); /* Move the navbar down slightly */
            padding: 50px 20px; /* Add padding */
            text-align: center; /* Center text */
        }
        .navbar-tertiary img {
            height: 400px; /* Set the height of the image */
            width: auto; /* Maintain aspect ratio */
            margin-right: 20px; /* Add margin to separate from text */
        }
        .get-started-button {
            background-color: white; /* White background */
            color: #71a2cf; /* Blue text color */
            border: none; /* No border */
            padding: 10px 20px; /* Add padding */
            font-size: 20px; /* Larger font size */
            border-radius: 5px; /* Rounded corners */
            cursor: pointer; /* Cursor style on hover */
            transition: background-color 0.3s; /* Smooth transition */
            margin-top: 20px; /* Add margin on top */
        }
        .get-started-button:hover {
            background-color: #f0f0f0; /* Light grey background on hover */
        }
        .jumbotron-custom {
            background-color: transparent; /* Remove background color */
            padding: 0; /* Remove padding */
            margin: 0; /* Remove margin */
        }
        .paw-icon-img {
            height: 60px; /* Adjust the height as needed */
            width: auto; /* Maintain aspect ratio */
            margin-right: 0px; /* Add margin to separate from text */
        }
        .navbar-nav {
            flex: 1; /* Allow the navbar to fill the space */
            justify-content: center; /* Center the navbar items */
            gap: 15px; /* Add gap between the items */
            margin-left: -180px; /* Shift items 20px to the left */
        }
    </style>
    <!-- Add FontAwesome for the paw icon -->
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
</head>
<body>
    {% block content_no_style %}
        <!-- Secondary Navbar -->
        <nav class="navbar navbar-expand-lg navbar-secondary">
            <div class="contact-text">Contact us at pawsplan1@gmail.com</div>
            {% if current_user.is_authenticated %}
                <div class="nav-item dropdown ml-auto">
                    <a class="nav-link dropdown-toggle user-email" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ current_user.email }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{{ url_for('main.logout') }}">Logout</a>
                    </div>
                </div>
            {% else %}
                <div class="auth-buttons">
                    <a class="nav-link" href="{{ url_for('main.register') }}">Register</a>
                    <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
                </div>
            {% endif %}
        </nav>
        <!-- Main Navbar -->
        <nav class="navbar navbar-expand-lg navbar-custom">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">
                <img src="https://www.edsaugusta.com/wp-content/uploads/2024/02/Paw-Print-Light-Blue-Transparent-01.png" alt="PawsPlan Logo" class="paw-icon-img">
                <i class="fas fa-paw paw-icon"></i>PawsPlan
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.dashboard') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.manage_pets') }}">Pets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.history_page') }}">History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.appointments') }}">Appointments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.vaccine_tracking') }}">Vaccinations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.feeding_schedule') }}">Feeding</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.expense_management') }}">Expenses</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block hideable_navbar %}
        <!-- Tertiary Navbar -->
        <div class="navbar-tertiary">
            <div>
                <div class="text-message" style="font-family: 'Poppins', sans-serif; font-size: 75px; margin-right: 20px;">
                    Your Pet's Health<br>Is Our Priority!
                </div>
                <!-- Add button below the text -->
                <button class="get-started-button" onclick="window.location.href='{{ url_for('main.register') }}'">Get Started</button>
            </div>
            <!-- Add an image in the blue navbar -->
            <img src="https://cdn.openart.ai/uploads/image_KizIvQxf_1715055673147_raw.png" alt="Your Image">
        </div>
        {% endblock %}
    {% endblock %}
    
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} mt-3">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/edit_appointment.html
{% extends "base.html" %}
{% block title %}Edit Appointment{% endblock %}
{% block hideable_navbar %}
<style>
    .navbar-tertiary {
        display: none;
    }
</style>
{% endblock %}
{% block content %}
    <style>
        body {
            background-image: url('https://assets.wfcdn.com/im/81456976/compr-r85/1178/117858037/fabric.jpg');
            background-size: cover;
            background-attachment: fixed;
            background-position: center;
            background-repeat: no-repeat;
        }
        .main-content {
            display: flex;
            justify-content: center;
            padding: 20px;
            margin-top: 20px;
            width: 100%;
        }
        .form-container {
            background-color: white;
            border-radius: 10px;
            padding: 20px;
            width: 100%;
            max-width: 600px;
            display: flex;
            flex-direction: column;
            position: relative; /* Add position relative to form-container */
        }
        .form-container h1 {
            font-size: 2em;
            margin-bottom: 20px;
            color: #71a2cf;
            text-align: center; /* Center the heading */
        }
        .form-container label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }
        .form-container input[type="text"],
        .form-container input[type="date"],
        .form-container input[type="time"],
        .form-container textarea,
        .form-container select {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
        }
        .form-container .btn-save {
            font-size: 1.2em;
            padding: 10px 20px;
            background-color: #71a2cf;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            display: block;
            margin: 0 auto; /* Center the button */
        }
        .form-container .btn-save:hover {
            background-color: #5a92c6;
        }
        .form-container .btn-back {
            font-size: 1.2em;
            padding: 10px 20px;
            background-color: #dc3545;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            position: absolute; /* Position the button */
            bottom: 20px;
            left: 20px; /* Position at the bottom left */
        }
        .form-container .btn-back:hover {
            background-color: #c82333;
        }
    </style>

    <div class="main-content">
        <div class="form-container">
            <h1>Edit Appointment</h1>
            <form method="post">
                {{ form.hidden_tag() }}
                <label for="pet">Pet</label>
                {{ form.pet }}
                
                <label for="date">Date</label>
                {{ form.date }}

                <label for="time">Time</label>
                {{ form.time }}

                <label for="vet_name">Vet Name</label>
                {{ form.vet_name }}

                <label for="description">Description</label>
                {{ form.description }}

                <button type="submit" class="btn-save">Save</button>
            </form>
            <a href="{{ url_for('main.appointments') }}" class="btn-back">Back</a> <!-- Added Back button -->
        </div>
    </div>
{% endblock %}

app/templates/manage_pets.html
{% extends "base.html" %}
{% block title %}Pet Management{% endblock %}
{% block hideable_navbar %}
<style>
    .navbar-tertiary {
        display: none;
    }
</style>
{% endblock %}
{% block content %}
<style>
    body {
        background-image: url('https://assets.wfcdn.com/im/81456976/compr-r85/1178/117858037/fabric.jpg');
        background-size: cover;
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
    }
    .main-content-container {
        display: flex;
        justify-content: center;
        padding: 20px;
        margin-top: 20px;
        width: 100%; /* Ensure it takes up the full width */
    }
    .main-content {
        background-color: white;
        border-radius: 10px;
        padding: 20px;
        width: 100%; /* Make the container take up the full width */
        max-width: 1200px; /* Ensure it doesn't grow too large on big screens */
        display: flex;
        flex-direction: column;
        align-items: center; /* Center align the content */
    }
    .main-content-header {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 100%;
        margin-bottom: 20px;
    }
    .main-content h1 {
        font-size: 3em;
        color: #71a2cf;
        text-align: center; /* Center the text */
    }
    .main-content .btn-add-pet {
        font-size: 1.2em;
        padding: 10px 20px;
        background-color: #71a2cf;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        text-decoration: none;
        margin-top: 40px;
    }
    .main-content .btn-add-pet:hover {
        background-color: #5a92c6;
    }
    .pet-list {
        width: 100%;
        display: flex;
        flex-direction: column;
        gap: 20px;
        align-items: center;
    }
    .pet-card {
        background-color: #f9f9f9;
        border: 1px solid #ddd;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        width: 100%; /* Full width for each card */
        display: flex;
        padding: 20px;
        align-items: center;
    }
    .pet-card img {
        width: 150px;
        height: 150px; /* Adjusted height for images */
        object-fit: cover;
        border-radius: 10px;
        margin-right: 20px;
    }
    .pet-info {
        flex-grow: 1;
        display: flex;
        flex-direction: column;
        justify-content: center;
    }
    .pet-info span {
        font-size: 1.2em;
        color: #333;
        margin-bottom: 5px;
    }
    .pet-actions {
        display: flex;
        flex-direction: column;
        align-items: center;
    }
    .btn-edit-pet, .btn-delete-pet, .btn-history {
        color: #fff;
        border: none;
        border-radius: 5px;
        padding: 5px 10px;
        cursor: pointer;
        margin-top: 5px;
        width: 100px;
        text-align: center;
    }
    .btn-edit-pet {
        background-color: #007bff;
    }
    .btn-edit-pet:hover {
        background-color: #0056b3;
    }
    .btn-history {
        background-color: #28a745; /* Light green color */
    }
    .btn-history:hover {
        background-color: #218838; /* Darker green on hover */
    }
    .btn-delete-pet {
        background-color: #dc3545;
    }
    .btn-delete-pet:hover {
        background-color: #c82333;
    }
</style>

<div class="main-content-container">
    <div class="main-content">
        <div class="main-content-header">
            <h1>Pet Management</h1>
        </div>
        <div class="pet-list">
            {% for pet in pets %}
                <div class="pet-card">
                    <img src="{{ url_for('static', filename='pet_pics/' ~ pet.picture) }}" alt="{{ pet.name }}">
                    <div class="pet-info">
                        <span>Name: {{ pet.name }}</span>
                        <span>Age: {{ pet.age }}</span>
                        <span>Breed: {{ pet.breed }}</span>
                        <span>Gender: {{ pet.gender }}</span> <!-- Add gender here -->
                    </div>
                    <div class="pet-actions">
                        <a href="{{ url_for('main.edit_pet', pet_id=pet.id) }}" class="btn-edit-pet">Edit</a>
                        <a href="{{ url_for('main.pet_history', pet_id=pet.id) }}" class="btn-history">History</a>
                        <form method="POST" action="{{ url_for('main.delete_pet', pet_id=pet.id) }}">
                            <button type="submit" class="btn-delete-pet" onclick="return confirm('Are you sure you want to delete this pet?');">Delete</button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a href="{{ url_for('main.add_pet') }}" class="btn-add-pet">Add Pet</a>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content_no_style %}
<style>
    html, body {
        height: 100%;
        margin: 0;
        font-family: 'Poppins', sans-serif;
    }
    body {
        background: linear-gradient(to bottom, #ffff, #71a2cf);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        padding: 20px;
        position: relative;
    }
    .logo-container {
        position: absolute;
        top: 20px;
        left: 20px;
    }
    .logo {
        text-decoration: none;
        color: black;
    }
    .logo img {
        height: 50px; /* Adjust the height as needed */
        width: auto; /* Maintain aspect ratio */
        vertical-align: middle;
    }
    .register-container {
        background-color: white;
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        max-width: 600px; /* Adjusted max-width */
        width: 100%;
    }
    h2 {
        color: #71a2cf;
        text-align: center;
    }
    .form-group {
        margin-bottom: 15px;
    }
    .btn-primary {
        background-color: #71a2cf;
        border: none;
        width: 100%;
    }
    .btn-primary:hover {
        background-color: #5a92b8;
    }
    .mt-3 {
        margin-top: 1rem !important;
    }
</style>
<script>
    function goBack() {
        window.history.back();
    }
</script>
<div class="logo-container" onclick="goBack()">
    <a href="#" class="logo">
        <img src="https://www.edsaugusta.com/wp-content/uploads/2024/02/Paw-Print-Light-Blue-Transparent-01.png" alt="PawsPlan Logo">
        PawsPlan
    </a>
</div>
<div class="register-container">
    <h2>Register To PawsPlan</h2>
    <form method="POST" action="{{ url_for('main.register') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {{ form.username(class="form-control form-control-lg") }}
        </div>
        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {{ form.email(class="form-control form-control-lg") }}
        </div>
        <div class="form-group">
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control form-control-lg") }}
        </div>
        <div class="form-group">
            {{ form.confirm_password.label(class="form-control-label") }}
            {{ form.confirm_password(class="form-control form-control-lg") }}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary btn-lg") }}
        </div>
    </form>
    <p class="mt-3">After registering, you will receive an email to verify your account.</p>
</div>
{% endblock %}